### ISSUE TITLE
Incorrect date from Danish CPR

### ISSUE THREAD

**Issue by artur-gajewski** [mathiasvr/danish-ssn#1]
I went to the following site:

http://id-check.artega.biz/index.php

I entered birthdate June 20, 2000 and used the first CPR found one the list: 200600-0005

According to your library component, when using the info("200600-0005").date I receive: 

Wed Jun 20 1900 00:00:00 GMT+0300 (EEST)

**Comment by mathiasvr** [comment]
Hi Artur,
The validator on that site seems to only perform the modulo 11 check, used for validating the CPR number. However even though the numbers are valid, they do not all belong to the same century.
This is decided by the 7th digit, and in the case of it being 0 as in `200600-0005` it can only belong to the year 1900.

You can use the following snippet to generate a list of CPR numbers that are valid for a specific date:
```javascript
cpr.validForDate(new Date(2000, 20, 6))
```

**Comment by mathiasvr** [comment]
Closing this for now, feel free to comment if you have any questions.
